name: Daily System Forecast Run

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'Trigger Source'
        required: false
        default: 'supabase'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache venv
      id: cache_venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ hashFiles('requirements_system_forecast.txt') }}

    - name: Install dependencies
      if: steps.cache_venv.outputs.cache-hit != 'true'

      run: |
        python -m venv .venv
        .venv_main/bin/pip install -r requirements_system_forecast.txt

    - name: Run script
      run: |
        .venv_main/bin/python system_forecast.py
      env:
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        EPIAS_USERNAME: ${{ secrets.EPIAS_USERNAME }}
        EPIAS_PASSWORD: ${{ secrets.EPIAS_PASSWORD }}
